### ISSUE TITLE
init_image

### ISSUE THREAD

**Issue by spot92** [ProGamerGov/neural-style-pt#50]
What does it mean to replace the initialization image?

**Comment by ProGamerGov** [comment]
By default an image composed of random pixel color values is used to start the style transfer process. If you use `-init image` then the image used to start the style transfer process is a copy of the content image. `-init_image` is used to replace this copy of the content image with a user specified third image.

The `-init_image` parameter was added to the original neural-style to improve multiscale generation (multires).

In the example below, a random initialization image is used for step 1. Then in order to speed up the multiscale generation process while preserving some information from the original content image, the past step's output is used to initialize the second style transfer step:

```
python3 neural_style.py -output_image out1.png -image_size 512

python3 neural_style.py -output_image out2.png -init image -init_image out1.png -image_size 720

python3 neural_style.py -output_image out3.png -init image -init_image out2.png -image_size 1024

python3 neural_style.py -output_image out4.png -init image -init_image out3.png -image_size 1536
```

**Comment by spot92** [comment]
Awesome, thanks

**Comment by ProGamerGov** [comment]
I've created two sets of guides which will farther illustrate how multiscale generation works along with how different parameters affect the output image:

https://github.com/ProGamerGov/neural-style-pt/wiki/Choosing-Parameters-for-Beginners

https://github.com/ProGamerGov/neural-style-pt/wiki/Multiscale-Generation-for-Beginners

**Comment by spot92** [comment]
Sweet! I will look at these. Thanks again for all this.

**Comment by spot92** [comment]
What video card was the tutorial/example run on?

**Comment by ProGamerGov** [comment]
Either a Tesla K80, or a Tesla T4.
